import { defineConfig } from "vite-plus";

// Generic thread contracts, adapter testing, and GitHub integration have separate public entries.
export default defineConfig({
  pack: {
    entry: [
      "src/index.ts",
      "src/ActivityStore.ts",
      "src/Admin.ts",
      "src/AgentRegistration.ts",
      "src/CommittedActivity.ts",
      "src/Digest.ts",
      "src/DurableAgentRuntime.ts",
      "src/DurableFailpoint.ts",
      "src/EventSource.ts",
      "src/GitHubWorkflowSource.ts",
      "src/OperationAuthorizer.ts",
      "src/PersistentHistory.ts",
      "src/PreparedInputAdmission.ts",
      "src/Records.ts",
      "src/Recovery.ts",
      "src/RunJournal.ts",
      "src/Schedule.ts",
      "src/ScheduleTransition.ts",
      "src/Scheduling.ts",
      "src/SqlMemoryStore.ts",
      "src/SubmissionLedger.ts",
      "src/SubmissionStatus.ts",
      "src/Subscription.ts",
      "src/SubscriptionInput.ts",
      "src/Subscriptions.ts",
      "src/SubscriptionTools.ts",
      "src/SubscriptionTransition.ts",
      "src/Certification.ts",
      "src/DurableFailpointTestControl.ts",
      "src/ScheduleStoreConformance.ts",
      "src/SubmissionLedgerConformance.ts",
      "src/SubscriptionStoreConformance.ts",
      "src/ThreadStoreConformance.ts",
      "src/ThreadInvariants.ts",
      "src/ThreadProjection.ts",
      "src/ThreadStore.ts",
      "src/ToolReconciler.ts",
      "src/WakeScheduler.ts",
    ],
    dts: true,
    sourcemap: true,
  },
  test: {
    cache: false,
    silent: "passed-only",
  },
});
