import { recommendedOxfmtConfig } from "@danieljvdm/dev-kit/oxfmt";
import { recommendedOxlintConfig } from "@danieljvdm/dev-kit/oxlint";
import { defineConfig } from "vite-plus";

const generatedPaths = [
  ".agents/**",
  ".claude/**",
  // Committed GitHub Action bundle (ADR-0016): generated by
  // scripts/build-action.ts, kept fresh by its own `bun run check` gate.
  "action/dist/**",
  "examples/demo/src/routeTree.gen.ts",
  "repos/**",
];

export default defineConfig({
  staged: {
    "*": "vp fmt --write",
  },
  fmt: {
    ...recommendedOxfmtConfig,
    ignorePatterns: generatedPaths,
  },
  lint: {
    extends: [recommendedOxlintConfig],
    ignorePatterns: generatedPaths,
    options: {
      typeAware: true,
      typeCheck: true,
    },
    jsPlugins: [{ name: "vite-plus", specifier: "vite-plus/oxlint-plugin" }],
    rules: {
      "import/no-duplicates": "warn",
      "react-hooks/exhaustive-deps": "warn",
      "stylistic/padding-line-between-statements": "warn",
      "typescript/consistent-type-imports": "warn",
      "typescript/no-non-null-assertion": "warn",
      "typescript/switch-exhaustiveness-check": "warn",
      "vitest/expect-expect": "warn",
      "vitest/no-conditional-expect": "warn",
      "vitest/require-to-throw-message": "warn",
      "vitest/valid-expect": "warn",
      "vitest/valid-title": "warn",
      "vite-plus/prefer-vite-plus-imports": "error",
    },
  },
  pack: {
    dts: true,
    format: ["esm"],
    sourcemap: true,
  },
  run: {
    cache: true,
  },
});
