// Column inventories from unpatched beta50 internal/migrations.ts.
export const v2Columns = {
  effect_agent_threads: [
    "thread_id",
    "created_at",
    "tail_sequence",
    "tail_digest",
    "producer_epoch",
  ],
  effect_agent_canonical_batches: [
    "thread_id",
    "batch_id",
    "first_sequence",
    "last_sequence",
    "batch_digest",
    "tail_digest",
    "batch_json",
  ],
  effect_agent_canonical_records: ["thread_id", "sequence", "record_id", "batch_id", "record_json"],
  effect_agent_checkpoints: ["thread_id", "through_sequence", "tail_digest", "checkpoint_json"],
  effect_agent_submissions: [
    "submission_id",
    "thread_id",
    "queue_sequence",
    "principal",
    "idempotency_key",
    "agent_id",
    "agent_digests_json",
    "deployment_id",
    "input_json",
    "input_digest",
    "receipt_id",
    "state",
    "settled_outcome",
    "created_at",
    "ready_at",
    "input_applied_record_id",
    "input_applied_sequence",
    "joined_host_submission_id",
    "suspended_reason_json",
    "suspended_at",
    "unknown_reason",
    "unknown_tool_call_ids_json",
    "parent_submission_id",
    "parent_tool_call_id",
  ],
  effect_agent_submission_ownership: [
    "submission_id",
    "attempt_id",
    "ownership_token",
    "producer_epoch",
    "owner_producer_id",
    "lease_expires_at",
  ],
  effect_agent_attempts: [
    "attempt_id",
    "submission_id",
    "thread_id",
    "owner_producer_id",
    "producer_epoch",
    "claimed_at",
  ],
  effect_agent_settlement_reservations: [
    "submission_id",
    "settlement_id",
    "outcome",
    "record_id",
    "record_json",
    "record_digest",
    "reserved_at",
    "finalized_at",
  ],
  effect_agent_abort_intents: [
    "submission_id",
    "author",
    "reason",
    "requested_at",
    "canonical_record_id",
  ],
  effect_agent_approval_decisions: [
    "submission_id",
    "tool_call_id",
    "decision",
    "resolver",
    "reason",
    "decided_at",
  ],
  effect_agent_unknown_resolutions: [
    "submission_id",
    "tool_call_id",
    "author",
    "reason",
    "resolution_json",
    "resolved_at",
  ],
  effect_agent_child_reservations: [
    "reservation_id",
    "parent_submission_id",
    "parent_tool_call_id",
    "child_submission_id",
    "status",
    "allocation_json",
    "allocation_digest",
    "accounting_json",
    "reserved_at",
    "release_began_at",
    "released_at",
  ],
  effect_agent_schedules: [
    "tenant_id",
    "owner_id",
    "schedule_id",
    "deadline_at_millis",
    "record_json",
  ],
  effect_agent_subscription_sequences: [
    "tenant_id",
    "source_address",
    "sequence",
    "event_scan_cursor",
    "delivery_scan_cursor",
    "recovery_scan_cursor",
  ],
  effect_agent_subscriptions: [
    "tenant_id",
    "source_address",
    "owner_id",
    "subscription_id",
    "ordinal",
    "source_name",
    "source_version",
    "matching_key",
    "state",
    "expires_at_millis",
    "recovery_at_millis",
    "record_json",
  ],
  effect_agent_subscription_events: [
    "tenant_id",
    "source_address",
    "event_id",
    "source_name",
    "source_version",
    "matching_key",
    "payload_digest",
    "cutoff",
    "cursor",
    "routing_complete",
    "next_attempt_at_millis",
    "record_json",
  ],
  effect_agent_subscription_deliveries: [
    "tenant_id",
    "source_address",
    "owner_id",
    "subscription_id",
    "event_id",
    "delivery_key",
    "state",
    "next_attempt_at_millis",
    "record_json",
  ],
} as const;
