import { defineConfig } from "vite-plus";

export default defineConfig({
  pack: {
    entry: [
      "src/index.ts",
      "src/Agent.ts",
      "src/AgentError.ts",
      "src/AgentPolicy.ts",
      "src/AgentRuntime.ts",
      "src/Approval.ts",
      "src/Budget.ts",
      "src/CodeMode.ts",
      "src/Commands.ts",
      "src/Compaction.ts",
      "src/ContextCompactor.ts",
      "src/DurableStep.ts",
      "src/EphemeralThreads.ts",
      "src/Identifiers.ts",
      "src/IdGenerator.ts",
      "src/Mcp.ts",
      "src/McpClient.ts",
      "src/Memory.ts",
      "src/MemoryNamespace.ts",
      "src/MemoryReference.ts",
      "src/MemoryRevalidation.ts",
      "src/MemoryStore.ts",
      "src/ModelContext.ts",
      "src/Redaction.ts",
      "src/RunEvent.ts",
      "src/RunEventSink.ts",
      "src/RunHooks.ts",
      "src/RunOptions.ts",
      "src/RunPolicyUsage.ts",
      "src/SemanticMemory.ts",
      "src/SemanticMemoryIndex.ts",
      "src/SemanticMemoryRevalidation.ts",
      "src/Subagent.ts",
      "src/SubagentContract.ts",
      "src/SubagentReservations.ts",
      "src/ThreadHistory.ts",
      "src/ToolBroker.ts",
      "src/ToolResult.ts",
      "src/Usage.ts",
      "src/WebCapture.ts",
    ],
    dts: true,
    sourcemap: true,
  },
  test: { cache: false, silent: "passed-only" },
});
