import { defineConfig } from "vite-plus";

export default defineConfig({
  pack: {
    entry: [
      "src/index.ts",
      "src/core/Agent.ts",
      "src/core/AgentError.ts",
      "src/core/AgentPolicy.ts",
      "src/engine/AgentRuntime.ts",
      "src/core/AgentUpdates.ts",
      "src/capabilities/Approval.ts",
      "src/capabilities/Budget.ts",
      "src/sandbox/CodeExecutor.ts",
      "src/capabilities/CodeMode.ts",
      "src/capabilities/Commands.ts",
      "src/engine/Compaction.ts",
      "src/engine/ContextCompactor.ts",
      "src/engine/ContextHistory.ts",
      "src/capabilities/ContextTools.ts",
      "src/engine/ContextWindow.ts",
      "src/engine/DurableStep.ts",
      "src/Ephemeral.ts",
      "src/engine/EphemeralThreads.ts",
      "src/core/IdGenerator.ts",
      "src/core/Identifiers.ts",
      "src/sandbox/InteractiveBrowser.ts",
      "src/capabilities/Mcp.ts",
      "src/capabilities/McpClient.ts",
      "src/core/Memory.ts",
      "src/core/MemoryNamespace.ts",
      "src/capabilities/MemoryNotes.ts",
      "src/core/MemoryReference.ts",
      "src/core/MemoryRevalidation.ts",
      "src/core/MemoryStore.ts",
      "src/capabilities/Messaging.ts",
      "src/engine/MessagingHost.ts",
      "src/capabilities/ModelContext.ts",
      "src/engine/Output.ts",
      "src/sandbox/PageCapture.ts",
      "src/sandbox/PageCrawl.ts",
      "src/sandbox/PageScreenshot.ts",
      "src/sandbox/ProtectedBrowser.ts",
      "src/core/Receipt.ts",
      "src/capabilities/Redaction.ts",
      "src/capabilities/Remembering.ts",
      "src/core/RememberingStore.ts",
      "src/core/RunEvent.ts",
      "src/engine/RunEventSink.ts",
      "src/capabilities/RunHooks.ts",
      "src/engine/RunOptions.ts",
      "src/core/RunPolicyUsage.ts",
      "src/sandbox/Sandbox.ts",
      "src/capabilities/SemanticMemory.ts",
      "src/core/SemanticMemoryIndex.ts",
      "src/core/SemanticMemoryRevalidation.ts",
      "src/capabilities/Subagent.ts",
      "src/core/SubagentContract.ts",
      "src/engine/SubagentHost.ts",
      "src/capabilities/SubagentReservations.ts",
      "src/engine/ThreadHistory.ts",
      "src/engine/ToolBroker.ts",
      "src/capabilities/ToolDiscovery.ts",
      "src/ToolExposure.ts",
      "src/core/ToolResult.ts",
      "src/core/Usage.ts",
      "src/capabilities/WebCapture.ts",
      "src/capabilities/WebSearch.ts",
      "src/core/Worker.ts",
    ],
    dts: true,
    sourcemap: true,
  },
  test: { cache: false, silent: "passed-only" },
});
